#!/usr/bin/env python3
"""Simple conversational test script for the orchestrator agent.
Just run: python simple_test.py
"""

import os
import sys
from uuid import uuid4
from dotenv import load_dotenv
from supabase import create_client
from getpass import getpass

# Load environment variables
load_dotenv()

# Add the app directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from app.agents.orchestrator import orchestratorAgent
from langchain_core.messages import HumanMessage

# Mock user database for testing
# To use these accounts, create them in your Supabase Dashboard:
# 1. Go to Authentication > Users
# 2. Click "Add User" and create each account below
# 3. The user_id will be auto-generated by Supabase (update here after creation)
MOCK_USERS = {
    "test@example.com": {
        "password": "password123",
        "user_id": "cmgmm7h8t0000vv3odxrsaah6",  # Update with real user_id from Supabase
        "name": "Test User"
    },
    "demo@example.com": {
        "password": "demo123",
        "user_id": "demo_user_12345",  # Update with real user_id from Supabase
        "name": "Demo User"
    }
}

def show_setup_instructions():
    """Show instructions for setting up test users"""
    print("\n" + "=" * 60)
    print("  🔧 SETUP REQUIRED")
    print("=" * 60)
    print("\nTo use mock login, create test users in Supabase:")
    print("\n1. Go to your Supabase Dashboard")
    print("2. Navigate to: Authentication > Users")
    print("3. Click 'Add User' and create:")
    print("\n   📧 test@example.com")
    print("   🔑 password123")
    print("\n   📧 demo@example.com")
    print("   🔑 demo123")
    print("\n4. Copy the generated user IDs and update MOCK_USERS in this script")
    print("\n" + "=" * 60 + "\n")

def mock_login():
    """Simulate user login and return authenticated session"""
    print("\n" + "=" * 60)
    print("  🔐 Mock Login System")
    print("=" * 60)
    print("\nAvailable test accounts:")
    print("  • test@example.com / password123")
    print("  • demo@example.com / demo123")
    print("  • Type 'skip' to use anon key")
    print("  • Type 'setup' for setup instructions\n")
    
    email = input("Email: ").strip()
    
    if email.lower() == 'skip':
        print("\n⚠️  Using anonymous key (limited RLS enforcement)")
        return None, None
    
    if email.lower() == 'setup':
        show_setup_instructions()
        return mock_login()  # Retry login after showing instructions
    
    password = getpass("Password: ")
    
    # Validate credentials
    if email in MOCK_USERS and MOCK_USERS[email]["password"] == password:
        user = MOCK_USERS[email]
        print(f"\n✓ Login successful! Welcome, {user['name']}")
        print(f"  User ID: {user['user_id']}")
        return user["user_id"], email
    else:
        print("\n✗ Invalid credentials. Using anonymous access.")
        return None, None

def create_authenticated_client(supabase_url, supabase_key, user_id=None, email=None):
    """Create a Supabase client with mock authentication"""
    client = create_client(supabase_url, supabase_key)
    
    if user_id and email:
        # Simulate JWT authentication by creating a mock session
        # In production, this would be a real JWT from Supabase Auth
        print(f"\n🔐 Creating authenticated session for {email}...")
        
        try:
            # Try to sign in with Supabase (if credentials exist)
            # This creates a REAL JWT token
            auth_response = client.auth.sign_in_with_password({
                "email": email,
                "password": MOCK_USERS.get(email, {}).get("password", "")
            })
            
            if auth_response.session:
                print("✓ Real JWT session created!")
                # Client now has real authentication
                return client, user_id
        except Exception as e:
            print(f"⚠️  Could not create real session: {e}")
            print("   Using mock authentication...")
    
    return client, user_id

def main():
    print("=" * 60)
    print("  Orchestrator Agent - Simple Test Console")
    print("=" * 60)
    
    # Get Supabase credentials
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_ANON_KEY")
    
    if not supabase_url or not supabase_key:
        print("\nError: SUPABASE_URL and SUPABASE_ANON_KEY must be set in .env file")
        return
    
    # Mock login to get user session
    test_user_id, email = mock_login()
    
    if not test_user_id:
        # Fallback to manual user ID entry
        print("\n" + "=" * 60)
        test_user_id = input("Enter user ID manually (or press Enter for default): ").strip()
        if not test_user_id:
            test_user_id = "cmgmm7h8t0000vv3odxrsaah6"
        email = None
    
    # Create authenticated Supabase client
    supabase, user_id = create_authenticated_client(
        supabase_url, 
        supabase_key, 
        test_user_id, 
        email
    )
    
    print("\n" + "=" * 60)
    print(f"  Session Active: User {test_user_id}")
    print("=" * 60)
    print("\nType your message and press Enter.")
    print("Commands: 'new' (new thread), 'session' (show session), 'quit' (exit)\n")
    
    thread_id = str(uuid4())
    print(f"Thread ID: {thread_id}\n")
    
    while True:
        try:
            # Get user input
            user_input = input("\nYou: ").strip()
            
            if not user_input:
                continue
            
            # Handle commands
            if user_input.lower() in ['quit', 'exit', 'q']:
                print("\nGoodbye!\n")
                break
            
            if user_input.lower() == 'new':
                thread_id = str(uuid4())
                print(f"\n✓ New thread started: {thread_id}\n")
                continue
            
            if user_input.lower() == 'session':
                print(f"\n📋 Current Session:")
                print(f"  User ID: {test_user_id}")
                print(f"  Email: {email or 'N/A'}")
                print(f"  Thread ID: {thread_id}")
                print(f"  Auth: {'Real JWT' if email else 'Anon Key'}\n")
                continue
            
            # Create state
            state = {
                "messages": [HumanMessage(content=user_input)],
                "context": user_input,
                "goal": "",
                "route_decision": "",
                "tasks": [],
                "agent_results": [],
                "final_response": "",
                "user_id": test_user_id,  # Pass user ID in state
                "user_timezone": "America/New_York",
            }
            
            # Config with thread and supabase client
            config = {
                "configurable": {
                    "thread_id": thread_id,
                    "supabase": supabase,  # Pass authenticated client
                    "user_id": test_user_id,  # Also in config for convenience
                }
            }
            
            # Invoke orchestrator
            print("\nProcessing...")
            try:
                result = orchestratorAgent.invoke(state, config=config)
                
                # Display response
                response = result.get("final_response", "")
                if response:
                    print(f"\nAssistant: {response}")
                else:
                    print("\n(No response generated)")
                    
            except Exception as e:
                print(f"\nError: {e}")
                
        except KeyboardInterrupt:
            print("\n\nInterrupted. Type 'quit' to exit.\n")
            continue
        except EOFError:
            print("\n\nGoodbye!\n")
            break

if __name__ == "__main__":
    main()
